// src/components/e2e-only-badge/index.tsx
import React from "react";
import s from "./style.module.css";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function E2EOnlyBadge() {
  return (
    <>
      <a href="/guides/core-concepts/testing-types#What-is-E2E-Testing">
        <div className={classNames(`${s.badge}`, `${s["hint"]}`)}>
          End-to-End Only
        </div>
      </a>
    </>
  );
}

// components/global/E2EOnlyBadge.vue
<script>
import Badge from './Badge'

export default {
  components: {
    Badge
  }
}
</script>

<template>
	<router-link 
  to="/guides/overview/choosing-testing-type#What-is-End-to-end-Testing"
  style="border-style: none">
		<Badge type="hint">End-to-End Only</Badge>
	</router-link>
</template>
