// components/global/DocsImage.vue
<script>
export default {
  props: {
    alt: {
      type: String,
      default: '',
    },
    src: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      default: '',
    },
    noBorder: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    filePath() {
      return require(`../../assets${this.src}`)
    },
  },
}
</script>

<template>
  <img
    :class="[$style.docsImage, { [$style.imageNoBorder]: noBorder }]"
    :src="filePath"
    :alt="alt"
    :title="title"
  />
</template>

<style module>
.docsImage {
  margin-bottom: 1rem;
}
.imageNoBorder {
  border: none !important;
  box-shadow: none !important;
}
</style>

// src/components/docs-image/index.tsx
import React from "react";
import s from "./style.module.css";
import { DocsImageProps } from "./types";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function DocsImage({
  alt,
  src,
  title,
  noBorder,
}: DocsImageProps) {
  return (
    <img
      className={classNames(
        `${s.docsImage}`,
        `${noBorder ? `${s.imageNoBorder}` : ""}`,
        "object-contain"
      )}
      src={src}
      alt={alt}
      title={title}
    />
  );
}
